[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "BioHackatonDE_annotations"
platforms = ["linux-64","win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
zeroc-ice = ">=3.6.5,<3.7"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
ngff-zarr = ">=0.20.0, <0.21"
omero-py = "==5.21.3"
ezomero = ">=1.1.1, <2"
bioio = ">=3.0.0, <4"
bioio-ome-tiff = ">=1.4.0, <2"
bioio-imageio = ">=1.3.0, <2"
dotenv = ">=0.9.9, <0.10"
napari = ">=0.6.5, <0.7"
napari-omero = ">=0.5.1, <0.6"
matplotlib = ">=3.10.7, <4"
